// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAqKOKwCYfwww8yqWsdJUEcBEqYUEC3P0',
    appId: '1:730604748847:web:5a934a945885877baf46da',
    messagingSenderId: '730604748847',
    projectId: 'grand-hotel-5adfc',
    authDomain: 'grand-hotel-5adfc.firebaseapp.com',
    storageBucket: 'grand-hotel-5adfc.firebasestorage.app',
    measurementId: 'G-NCPD43E72N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-yh8zJcsomUrDuEtlzEYUj6GVHZXlRkI',
    appId: '1:730604748847:android:2630cbf63b37b508af46da',
    messagingSenderId: '730604748847',
    projectId: 'grand-hotel-5adfc',
    storageBucket: 'grand-hotel-5adfc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNx3IJcQIvhUaDz0tGvDiRpolgN12FiKA',
    appId: '1:730604748847:ios:24ae1b47c5a26adfaf46da',
    messagingSenderId: '730604748847',
    projectId: 'grand-hotel-5adfc',
    storageBucket: 'grand-hotel-5adfc.firebasestorage.app',
    iosBundleId: 'com.example.grandHotel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNx3IJcQIvhUaDz0tGvDiRpolgN12FiKA',
    appId: '1:730604748847:ios:24ae1b47c5a26adfaf46da',
    messagingSenderId: '730604748847',
    projectId: 'grand-hotel-5adfc',
    storageBucket: 'grand-hotel-5adfc.firebasestorage.app',
    iosBundleId: 'com.example.grandHotel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAqKOKwCYfwww8yqWsdJUEcBEqYUEC3P0',
    appId: '1:730604748847:web:fbfee2664e0561fbaf46da',
    messagingSenderId: '730604748847',
    projectId: 'grand-hotel-5adfc',
    authDomain: 'grand-hotel-5adfc.firebaseapp.com',
    storageBucket: 'grand-hotel-5adfc.firebasestorage.app',
    measurementId: 'G-CZT5ZYEL0Q',
  );
}
